Small changes
Breezy-Traveler/Breezy-iOS pull request #150
Opened 2018-11-16 16:47 UTC by LinnierGames

closes #149 #145 

### Changes Made
- Removed Name TextField from Register Screen
> The heights of the `inputContainerHeight` are slightly different than before removing the name text field

- Checked and removed all retain cycles in Closures
> This included some closures with `unowned` in their capture lists. They were changed to `weak`

- Added `.gitattributes`
> Cross our fingers this will fix the conflicts in the `*.pbxproj` files

2018-11-16 20:23 UTC, phylliswong requested changes
perhaps named for what you fixed.

2018-11-16 21:26 UTC, LinnierGames commented
@PhyllisWong in your review, do you mean the name of this PR is inappropriate for the changes I made? If so, I do agree. I just noticed there are a lot of more commits on this PR than I intended. I'll look later today for these *extra* commits.

2018-11-18 22:05 UTC, LinnierGames commented
@PhyllisWong I've updated the timeline of commits this PR will merge into `develop`. I needed to refresh the `base` branch. So now, it only shows three commits and I've made note of what these commits do in the body of this PR.

Let me know if you'd like me to give a more appropriate PR title.

2018-11-19 21:09 UTC, phylliswong approved these changes

2018-11-19 21:09 UTC, merged